Repository checkmarx-ltd/cxvscode, pull requests merged in 2020-07, with the labels that each got.

#3 Applied downstream PR and fixed some issues
  README.md
  package-lock.json
  package.json
  src/extension.ts
  src/interface/INode.ts
  src/model/CxTreeDataProvider.ts
  src/model/CxTreeScans.ts
  src/model/ScanNode.ts
  src/model/ServerNode.ts
  src/services/CxSettings.ts
Labels: size/L

#4 Feature/disable scan buttons
  package.json
  src/extension.ts
  src/services/CxSettings.ts
Labels: size/M

#7 Fixed #6 - Scan results not visible on Linux and macOS
  src/services/WebViews.ts
Labels: size/S

#8 Feature/retrieve latest result
  .gitignore
  src/extension.ts
  src/model/ScanNode.ts
  src/model/ServerNode.ts
Labels: size/S

#10 Implemented SSO login and fixed get last results of bound projects
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/extension.ts
  src/model/CxTreeScans.ts
  src/model/LoginMethods.ts
  src/model/ScanNode.ts
  src/model/ServerNode.ts
  src/services/CxSettings.ts
  src/services/WebViews.ts
Labels: size/L

#11 Added support for publishing VSC plugin to marketplace
  azure-pipelines.yml
  package.json
Labels: size/S
