Repository checkmarx-ltd/cxvscode, pull requests merged in 2021-09, with the labels that each got.

#36 Disable publish to marketplace. Instead, upload to artifactory
  azure-pipelines.yml
Labels: size/S

#37 Saml enhancement defect fixes
  README.md
  attackVectorWebView.html
  package-lock.json
  package.json
  resultTableWebView.html
  src/extension.ts
  src/model/CxTreeDataProvider.ts
  src/model/CxTreeScans.ts
  src/model/LoginMethods.ts
  src/model/ScanNode.ts
  src/model/ServerNode.ts
  src/model/ssoConstant.ts
  src/services/CxSettings.ts
  src/services/SSOUriHandler.ts
  src/services/WebViews.ts
  src/services/loginChecks.ts
  src/services/sastClient.ts
  src/services/sessionStorageService.ts
Labels: size/XL

#38 Fixed the ui log left for filtering issue
  resultTableWebView.html
Labels: size/XS
