Repository checkmarx-ltd/cxvscode, pull requests merged in 2021-08, with the labels that each got.

#24 SSO support to VSCode Plugin
  src/extension.ts
  src/model/CxTreeDataProvider.ts
  src/model/ScanNode.ts
  src/model/ServerNode.ts
  src/model/ssoConstant.ts
  src/services/SSOUriHandler.ts
  src/services/WebViews.ts
  src/services/loginChecks.ts
  src/services/sastClient.ts
  src/services/sessionStorageService.ts
Labels: size/L

#25 Vscodefiltering ncolumns
  attackVectorWebView.html
  resultTableWebView.html
Labels: size/L

#28 changed login option name
  src/model/LoginMethods.ts
  src/model/ServerNode.ts
  src/services/CxSettings.ts
Labels: size/M

#27 CodeSmellFixes VSCode
  src/model/ServerNode.ts
  src/services/WebViews.ts
  src/services/loginChecks.ts
Labels: size/L

#29 Update resultTableWebView.html & fixed filtering bug
  resultTableWebView.html
Labels: size/S

#30 Remediation changes
  resultTableWebView.html
  src/services/WebViews.ts
Labels: size/M

#31 added changes in paskage.json file
  package.json
Labels: size/XS

#33 Added SSL certificate path fields in settings
  package.json
  src/model/ServerNode.ts
  src/services/CxSettings.ts
Labels: size/S

#32 Support triage change state
  resultTableWebView.html
  src/model/ScanNode.ts
  src/model/ServerNode.ts
  src/services/WebViews.ts
Labels: size/L

#35 Committed review comments
  package.json
  resultTableWebView.html
  src/extension.ts
  src/model/CxTreeDataProvider.ts
  src/model/CxTreeScans.ts
  src/model/ServerNode.ts
  src/services/CxSettings.ts
  src/services/SSOUriHandler.ts
  src/services/WebViews.ts
Labels: size/M
