Repository checkmarx-ltd/cxvscode, pull requests merged in 2023-07, with the labels that each got.

#55 fixed PLUG-1169 by addign a reverse() fucntion to projectList
  src/model/ServerNode.ts
Labels: size/XS

#56 added event.stopPropagation() to prevent the source file & attack vec…
  resultTableWebView.html
Labels: size/XS

#52 Plug 902
  package.json
  src/interface/INode.ts
  src/model/CxTreeDataProvider.ts
  src/model/CxTreeScans.ts
  src/model/QueryNode.ts
  src/model/ScanNode.ts
  src/model/SeverityNode.ts
Labels: size/M

#53 Changes related to results table
  resultTableWebView.html
Labels: size/L

#58 Qa bug fixes
  resultTableWebView.html
  src/model/CxTreeDataProvider.ts
  src/services/WebViews.ts
Labels: size/XS

#59 Plug 1168
  package.json
  src/extension.ts
  src/model/CxTreeDataProvider.ts
  src/model/EmptyCxTreeScans.ts
Labels: size/M
