Repository checkmarx-ltd/cxvscode, pull requests merged in 2024-03, with the labels that each got.

#70 Q1 integration 2024 bug fixes
  package.json
  resultTableWebView.html
  src/model/ServerNode.ts
Labels: size/M

#68 Q1 2024 integration branch
  attackVectorWebView.html
  package.json
  resultTableWebView.html
  src/model/CxPluginDetails.ts
  src/model/QueryNode.ts
  src/model/ServerNode.ts
  src/services/CxSettings.ts
  src/services/WebViews.ts
Labels: size/XXL

#71 Update package.json
  package.json
Labels: size/XS
